### ISSUE TITLE
Dump config to config.json

### ISSUE THREAD

**Issue by LukeWood** [LukeWood/bocas#13]

**Comment by caharper** [comment]
@LukeWood I can take on this one.  I think .yaml is a better fit than .json since it can support custom types and is more human readable.

**Comment by caharper** [comment]
Here is an example .yaml after running with bocas:

```yaml
!Result
artifacts:
- !KerasHistory
  history:
    acc:
    - 0.08392000198364258
    - 0.10016000270843506
    loss:
    - 2.2971956729888916
    - 2.294981002807617
    lr:
    - !np.float32 '1e-04'
    - !np.float32 '1e-04'
    val_acc:
    - 0.09548000246286392
    - 0.09498000144958496
    val_loss:
    - 2.296081781387329
    - 2.29384446144104
  name: history
- !Metrics
  metrics:
    acc: 0.09359999746084213
    loss: 2.2937772274017334
  name: metrics
config: !ConfigDict
  batch_size: 128
  epochs: 2
  model_type: Example
  size: 1
  version: v0.1
name: 1_09_24_23_07_42_v0.1
```
